### PR TITLE
fix klipper crash if selected tool restore fails during printing

### PR DESCRIPTION
**Pull request by bakatrouble**
Just moved try...except statements around

### CODE REVIEW

**Comment by moggieuk** [comment]
What was the error on _select_tool()?   I ask because that should really generate an MmuError if it fails and cause a "mmu pause".  It shouldn't cause a klipper crash.

The concern I have with this patch is that rather than pausing a print as intended it will hide the tool restore error by simply issuing a message but nothing more...

**Comment by bakatrouble** [comment]
I reverted my change, will follow up once I encounter it again, I don't remember how exactly it is triggered already

**Comment by bakatrouble** [comment]
Didn't have to wait long, though got one in a different place, the filament got stuck in a tube while unloading:
```
Traceback (most recent call last):
  File "/home/klipper/klipper/klippy/extras/mmu.py", line 4317, in _unload_sequence
    self._unload_gate()
  File "/home/klipper/klipper/klippy/extras/mmu.py", line 3832, in _unload_gate
    raise MmuError("Unloading gate failed")
extras.mmu.MmuError: Unloading gate failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/klipper/klipper/klippy/extras/mmu.py", line 5517, in cmd_MMU_EJECT
    self._unload_tool(skip_tip=skip_tip)
  File "/home/klipper/klipper/klippy/extras/mmu.py", line 5183, in _unload_tool
    self._unload_sequence(skip_tip=skip_tip, runout=runout)
  File "/home/klipper/klipper/klippy/extras/mmu.py", line 4348, in _unload_sequence
    raise MmuError("Unload sequence failed: %s" % (str(ee)))
extras.mmu.MmuError: Unload sequence failed: Unloading gate failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/klipper/klipper/klippy/extras/virtual_sdcard.py", line 273, in work_handler
    self.gcode.run_script(line)
  File "/home/klipper/klipper/klippy/gcode.py", line 231, in run_script
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/klipper/klipper/klippy/gcode.py", line 213, in _process_commands
    handler(gcmd)
  File "/home/klipper/klipper/klippy/gcode.py", line 137, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/klipper/klipper/klippy/extras/gcode_macro.py", line 189, in cmd
    self.template.run_gcode_from_command(kwparams)
  File "/home/klipper/klipper/klippy/extras/gcode_macro.py", line 68, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/klipper/klipper/klippy/gcode.py", line 228, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/klipper/klipper/klippy/gcode.py", line 213, in _process_commands
    handler(gcmd)
  File "/home/klipper/klipper/klippy/gcode.py", line 137, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/klipper/klipper/klippy/extras/gcode_macro.py", line 189, in cmd
    self.template.run_gcode_from_command(kwparams)
  File "/home/klipper/klipper/klippy/extras/gcode_macro.py", line 68, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/klipper/klipper/klippy/gcode.py", line 228, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/klipper/klipper/klippy/gcode.py", line 213, in _process_commands
    handler(gcmd)
  File "/home/klipper/klipper/klippy/gcode.py", line 137, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/klipper/klipper/klippy/extras/mmu.py", line 5527, in cmd_MMU_EJECT
    self._mmu_pause(str(ee))
  File "/home/klipper/klipper/klippy/extras/mmu.py", line 2918, in _mmu_pause
    self._recover_filament_pos(strict=False, message=True)
  File "/home/klipper/klipper/klippy/extras/mmu.py", line 4362, in _recover_filament_pos
    if self._check_filament_still_in_extruder():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/klipper/klipper/klippy/extras/mmu.py", line 4949, in _check_filament_still_in_extruder
    _,_,measured,_ = self._trace_filament_move("Checking extruder", -length, speed=self.extruder_unload_speed, motor="extruder")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/klipper/klipper/klippy/extras/mmu.py", line 4791, in _trace_filament_move
    with self._wrap_sync_extruder_to_gear(motor in ["gear+extruder", "extruder"], extruder_only=(motor == "extruder")):
  File "/home/klipper/.pyenv/versions/3.11.3/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/klipper/klipper/klippy/extras/mmu.py", line 5053, in _wrap_sync_extruder_to_gear
    self.mmu_toolhead.sync_extruder_to_gear(None)
  File "/home/klipper/klipper/klippy/extras/mmu_toolhead.py", line 281, in sync_extruder_to_gear
    self.flush_step_generation()
  File "/home/klipper/klipper/klippy/toolhead.py", line 371, in flush_step_generation
    self._flush_lookahead()
  File "/home/klipper/klipper/klippy/toolhead.py", line 365, in _flush_lookahead
    self.lookahead.flush()
  File "/home/klipper/klipper/klippy/toolhead.py", line 176, in flush
    self.toolhead._process_moves(queue[:flush_count])
  File "/home/klipper/klipper/klippy/toolhead.py", line 362, in _process_moves
    self._advance_move_time(next_move_time)
  File "/home/klipper/klipper/klippy/toolhead.py", line 320, in _advance_move_time
    self._advance_flush_time(flush_time)
  File "/home/klipper/klipper/klippy/toolhead.py", line 311, in _advance_flush_time
    m.flush_moves(flush_time, clear_history_time)
  File "/home/klipper/klipper/klippy/mcu.py", line 976, in flush_moves
    raise error("Internal error in MCU '%s' stepcompress"
mcu.error: Internal error in MCU 'ebb' stepcompress
Exiting SD card print (position 6797952)
Internal error on command:"MMU_EJECT"
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown
```

**Comment by moggieuk** [comment]
I think I'm going to need the full `klippy.log`...

You can see the klipper "stepcompress" error.  This is a fundamental error that does crash klipper.  It is caused when two steppers with widely different "rotational step distance" are moved in sync.  Have a read here: https://github.com/moggieuk/Happy-Hare/wiki/Troubleshooting-and-Common-Issues#-klipper-internal-step-compress-error

It is easy to fix.

If this is the root cause then trying to mask it is not the right thing to do.

Again, if I can review the whole `klippy.log` I can be sure.

**Comment by moggieuk** [comment]
I'm going to close out this PR / Issue because I don't believe it is necessary.  Please reopen if you disagree and can provide a `klippy.log` (with the stepcompress error).

**Pull request closed without merging**
