### PR TITLE
Allow to use fysetc erb v2

### PR DESCRIPTION
**Pull request by gdachs**
You have the pinout for the fysetc erb v2 in the install script, but no way to use it.

btw, it doesn't work to set unused aliases to '', klipper will not start.

### CODE REVIEW

**Comment by moggieuk** [comment]
Thanks. I was waiting for the launch of ERB v2 :-). 

I think an unused alias must be simply empty, but I'm not sure.

Anyway, I'l get to this PR shortly!

**Comment by gdachs** [comment]
> Thanks. I was waiting for the launch of ERB v2 :-).

I even don't know that I own a v2. I just noticed that my pins match with the config you name v2 ;)

**Comment by gdachs** [comment]
I have just checked my board, sorry should have done this beforehand:
. It has the version V1.1, but as mentioned, it has the pinout of your V2.

Yesterday I started to ask some questions to Happy Hare in the discord of Vorondesign in ercf_questions and in Annex Engineering in tr_general. I would prefer the later as I use a tradrack. Did not get any reactions till now. Is there a better place?

**Comment by moggieuk** [comment]
Ah.  Ok. v1.1.  I'll check.   Maybe I let the cat out of the bag on v2 then. Ooops.

**Comment by moggieuk** [comment]
Sorry for delay.  Can you help me by first giving me the list of pins for your v1.1 board, or does it matches one of these (I thought the v1.1 board was the same pin out as the v1.0 board but I could be wrong):

```
# Pins for Fysetc Burrows ERB board (original v1 and v2)
#
PIN[ERB,gear_uart_pin]="gpio20";           PIN[ERBv2,gear_uart_pin]="gpio20";
PIN[ERB,gear_step_pin]="gpio10";           PIN[ERBv2,gear_step_pin]="gpio10";
PIN[ERB,gear_dir_pin]="gpio9";             PIN[ERBv2,gear_dir_pin]="gpio9";
PIN[ERB,gear_enable_pin]="gpio8";          PIN[ERBv2,gear_enable_pin]="gpio8";
PIN[ERB,gear_diag_pin]="gpio13";           PIN[ERBv2,gear_diag_pin]="gpio13";
PIN[ERB,selector_uart_pin]="gpio17";       PIN[ERBv2,selector_uart_pin]="gpio17";
PIN[ERB,selector_step_pin]="gpio16";       PIN[ERBv2,selector_step_pin]="gpio16";
PIN[ERB,selector_dir_pin]="gpio15";        PIN[ERBv2,selector_dir_pin]="gpio15";
PIN[ERB,selector_enable_pin]="gpio14";     PIN[ERBv2,selector_enable_pin]="gpio14";
PIN[ERB,selector_diag_pin]="gpio19";       PIN[ERBv2,selector_diag_pin]="gpio19";
PIN[ERB,selector_endstop_pin]="gpio24";    PIN[ERBv2,selector_endstop_pin]="gpio24";
PIN[ERB,servo_pin]="gpio23";               PIN[ERBv2,servo_pin]="gpio23";
PIN[ERB,encoder_pin]="gpio22";             PIN[ERBv2,encoder_pin]="gpio22";
PIN[ERB,neopixel_pin]="gpio21";            PIN[ERBv2,neopixel_pin]="gpio21";
PIN[ERB,gate_sensor_pin]="gpio22";         PIN[ERBv2,gate_sensor_pin]="gpio25";  # Hall Effect
PIN[ERB,pre_gate_0_pin]="gpio0";           PIN[ERBv2,pre_gate_0_pin]="gpio12";
PIN[ERB,pre_gate_1_pin]="gpio1";           PIN[ERBv2,pre_gate_1_pin]="gpio18";
PIN[ERB,pre_gate_2_pin]="gpio2";           PIN[ERBv2,pre_gate_2_pin]="gpio2";
PIN[ERB,pre_gate_3_pin]="gpio3";           PIN[ERBv2,pre_gate_3_pin]="gpio3";
PIN[ERB,pre_gate_4_pin]="gpio4";           PIN[ERBv2,pre_gate_4_pin]="gpio4";
PIN[ERB,pre_gate_5_pin]="gpio5";           PIN[ERBv2,pre_gate_5_pin]="gpio5";
PIN[ERB,pre_gate_6_pin]="gpio6";           PIN[ERBv2,pre_gate_6_pin]="gpio6";
PIN[ERB,pre_gate_7_pin]="gpio7";           PIN[ERBv2,pre_gate_7_pin]="gpio7";
PIN[ERB,pre_gate_8_pin]="gpio26";          PIN[ERBv2,pre_gate_8_pin]="gpio26";
PIN[ERB,pre_gate_9_pin]="gpio27";          PIN[ERBv2,pre_gate_9_pin]="gpio27";
PIN[ERB,pre_gate_10_pin]="gpio28";         PIN[ERBv2,pre_gate_10_pin]="gpio28";
PIN[ERB,pre_gate_11_pin]="gpio29";         PIN[ERBv2,pre_gate_11_pin]="gpio29";
```

**Comment by moggieuk** [comment]
I'm going to close this particular PR because support for new MMU boards was added to the early access v2.6.0. I believe I have the support you require.  If there are still omissions please re-open the PR after checking against v2.6.0. Thanks.

**Pull request closed without merging**
